# Site settings
title: Jekyll/Bootstrap
description: A starter Jekyll site for use with GitHub Pages. Includes Bootstrap baked right in.
baseurl: "/jekyll-bootstrap" # the subpath of your site, e.g. /blog
url: "https://robertlove.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

# SASS
sass:
  style: :compressed

# Exclude
exclude:
  - assets/js/bootstrap.js
  - assets/js/jquery.js
  - assets/js/popper.js
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
