# Site settings
title: Jekyll/Bootstrap
description: A Jekyll starter project for GitHub Pages with Bootstrap 4.3.1 baked right in!
baseurl: "/jekyll-bootstrap" # the subpath of your site, e.g. /blog
url: "https://robertlove.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

# SASS
sass:
  style: :compressed

# Defaults
defaults:
  - scope:
      path: "*"
    values:
      layout: default

# Exclude
exclude:
  - assets/js/bootstrap.min.js
  - assets/js/jquery.min.js
  - assets/js/popper.min.js
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
