# Site settings
title: ILiADS
description: Institute of Liberal Arts Digital Scholarship
url: "https://iliads.github.io/website" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: ""

# Build settings
markdown: kramdown

# SASS
sass:
  style: :compressed

# Defaults
defaults:
  - scope:
      path: "*"
    values:
      layout: default

# Exclude
exclude:
  - assets/js/bootstrap.bundle.min.js
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# Collections
collections:
  about:
      output: true
      permalink: /about/:name:output_ext
  twenty-four:
    output: true
    permalink: /2024/:name:output_ext
